[project]
name = "ku-dis-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "jinja2>=3.1.6",
    "psycopg2>=2.9.10",
]
